### ISSUE TITLE
bad compilation

### ISSUE THREAD

**Issue by D3fau4** [Reisyukaku/ReiNXToolkit#11]
hello, I'm trying to compile your program, and it compiles[ correctly](https://pastebin.com/6WiTAA72) but the size of the .nro it generates is very different from yours, I can execute it perfectly but the sources do not work
![compile](https://user-images.githubusercontent.com/19638408/49341037-2d20c280-f648-11e8-93e5-694e8215c847.PNG)
![tool](https://user-images.githubusercontent.com/19638408/49341038-2d20c280-f648-11e8-8b55-363fc85d8cfc.PNG)
![img_20181202_152831](https://user-images.githubusercontent.com/19638408/49341041-3b6ede80-f648-11e8-8ccc-22fb41ebd6a8.jpg)

**Comment by Reisyukaku** [comment]
Have you updated to latest pacman SDL2, libnx etc?

**Comment by D3fau4** [comment]
Yes of course, I have tried to compile it with Ubuntu and MSYS2 and I have obtained the same result.

**Comment by Reisyukaku** [comment]
Theres only one other person that had this issues and we have no idea why .. i'd image its a font issue but the font is in the romfs.

**Comment by thomleg50** [comment]
I have the same problem

**Comment by ThatNerdyPikachu** [comment]
THOMLEG!!!!

**Comment by SpinAttack** [comment]
Same issue for me, OpenSUSE Leap.
