### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Linderkin** [Reisyukaku/ReiNXToolkit#6]
Hi,
I use devkitpro for windows and I have an error at end compilation and I don't found solution for this

> /Request.hpp:22:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: UI.o] Error 1
make: *** [Makefile:168: build] Error 2

**Comment by Reisyukaku** [comment]
try installing libcurl via msys2

**Comment by Linderkin** [comment]
same mistake
![captura](https://user-images.githubusercontent.com/7673564/47133144-ac7c5180-d2a7-11e8-80ba-5ce1608a4e26.JPG)
